import 'package:easy_localization/easy_localization.dart';

class AppLocalizationsString {
  static String get email => "Email".tr();
  static String get password => "Password".tr();
  static String get login => "Login".tr();
  static String get signUp => "Sign up".tr();
  static String get username => "Username".tr();
  static String get forgotPassword => "Forgot your password?".tr();
  static String get resetNow => "Reset now".tr();
  static String get continueAsGuest => "Continue as guest".tr();
  static String get passwordConfirm => "Password Confirm".tr();
  static String get bySigningUp => "By signing up, you agree to our Terms of Service and Privacy Policy.".tr();
  static String get privacyPolicy => "Privacy Policy".tr();
  static String get terms => "and Terms".tr();
  static String get welcome => "Welcome".tr();
  static String get enjoyAndRelax => "Enjoy and relax together".tr();
  static String get discoverWorld => "Let's discover the world".tr();
  static String get laughterAndPlay => "Laughter and play starts here".tr();
  static String get next => "Next".tr();
  static String get skip => "Skip".tr();
  static String get recommended => "Recommended".tr();
  static String get atLeast1Lowercase => "At least 1 lowercase letter".tr();
  static String get atLeast1Uppercase => "At least 1 uppercase letter".tr();
  static String get atLeast1SpecialCharacter => "At least 1 special character".tr();
  static String get atLeast1Number => "At least 1 number".tr();
  static String get atLeast8Characters => "At least 8 characters ".tr();
  static String get search => "search".tr();
  static String get trips => "trips".tr();
  static String get kashta => "kashta".tr();
  static String get activities => "activities".tr();
  static String get stores => "stores".tr();
  static String get popularDestinations => "popular_destinations".tr();
  static String get showMore => "show_more".tr();
  static String get topActivities => "top_activities".tr();
  static String get viewAll => "view_all".tr();
  static String get topStore => "top_store".tr();
  static String get home => "Home".tr();
  static String get categories => "Categories".tr();
  static String get bookings => "Bookings".tr();
  static String get cart => "Cart".tr();
  static String get profile => "Profile".tr();
  static String get send => "send".tr();
  static String get weWillSendYouAnEmail => "We will send".tr();
  static String get guests => "guests".tr();
  static String get bedroom => "bedroom".tr();
  static String get bathroom => "bathroom".tr();
  static String get egyptian => "Egyptian".tr();
  static String get halls => "Halls".tr();
  static String get m2 => "M2".tr();
  static String get description => "Description".tr();
  static String get comfortFacilities => "Comfort Facilities".tr();
  static String get bookNow => "Book now".tr();
  static String get back => "back".tr();
  static String get details => "details".tr();
  static String get wild => "Wild".tr();
  static String get sorry => "Sorry".tr();
  static String get somethingWentWrong => "Something went wrong".tr();
  static String get notAvailableStayTuned => "are not available at the moment. Stay tuned for more soon!".tr();
  static String get userDisabled => "user_disabled".tr();
  static String get invalidCredential => "invalid_credential".tr();
  static String get tooManyRequests => "too_many_requests".tr();
  static String get networkRequestFailed => "network_request_failed".tr();
  static String get emailAlreadyInUse => "email_already_in_use".tr();
  static String get userNotFound => "user_not_found".tr();
  static String get weakPassword => "weak_password".tr();
  static String get genericError => "generic_error".tr();
  static String get loginError => "login failure".tr();
  static String get signUpError => "signup failure".tr();
  static String get doesNotMatch => "doesn't match".tr();
  static String get shouldNotBeEmpty => "shouldn't be empty".tr();
  static String get pleaseEnterValidEmail => "Please enter a valid email".tr();
  static String get kwdCurrency => "kwd".tr();
  static String get sale => "sale".tr();
  static String get addToCart => "add_to_cart".tr();
  static String get buyNow => "buy_now".tr();
  static String get youMightLikeThis => "you_might_like_this".tr();
  static String get notSpecified => "not_specified".tr();
  static String get notRated => "not_rated".tr();




}
