// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRceLn4biEh2QnJJQS1H19HonPG-84oR0',
    appId: '1:67174363204:web:b94b8fa3fa6d0a91388c11',
    messagingSenderId: '67174363204',
    projectId: 'tjhaz-3d2f3',
    authDomain: 'tjhaz-3d2f3.firebaseapp.com',
    databaseURL: 'https://tjhaz-3d2f3-default-rtdb.firebaseio.com',
    storageBucket: 'tjhaz-3d2f3.firebasestorage.app',
    measurementId: 'G-66E0QWP1DV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzmFoHX7o17DV0YEWpiINSE18qZ09flH4',
    appId: '1:67174363204:android:2509729a40167e30388c11',
    messagingSenderId: '67174363204',
    projectId: 'tjhaz-3d2f3',
    databaseURL: 'https://tjhaz-3d2f3-default-rtdb.firebaseio.com',
    storageBucket: 'tjhaz-3d2f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbT2cZC94CPXI_e7JuNrtscsT90MUAGW4',
    appId: '1:67174363204:ios:84f426c4d42007cc388c11',
    messagingSenderId: '67174363204',
    projectId: 'tjhaz-3d2f3',
    databaseURL: 'https://tjhaz-3d2f3-default-rtdb.firebaseio.com',
    storageBucket: 'tjhaz-3d2f3.firebasestorage.app',
    iosBundleId: 'com.example.tjhaz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbT2cZC94CPXI_e7JuNrtscsT90MUAGW4',
    appId: '1:67174363204:ios:84f426c4d42007cc388c11',
    messagingSenderId: '67174363204',
    projectId: 'tjhaz-3d2f3',
    databaseURL: 'https://tjhaz-3d2f3-default-rtdb.firebaseio.com',
    storageBucket: 'tjhaz-3d2f3.firebasestorage.app',
    iosBundleId: 'com.example.tjhaz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRceLn4biEh2QnJJQS1H19HonPG-84oR0',
    appId: '1:67174363204:web:0ee9ac40c8119369388c11',
    messagingSenderId: '67174363204',
    projectId: 'tjhaz-3d2f3',
    authDomain: 'tjhaz-3d2f3.firebaseapp.com',
    databaseURL: 'https://tjhaz-3d2f3-default-rtdb.firebaseio.com',
    storageBucket: 'tjhaz-3d2f3.firebasestorage.app',
    measurementId: 'G-Y0S003C3SF',
  );
}
